[env._]
path = [
  "{{config_root}}/node_modules/.bin",
]
file = { path = "android/signing/creds.env.json", redact = true }

[settings.sops]
age_key_file = "~/.config/age/key.txt"

[deps.flutter]
auto = true

[tasks.test]
run = "flutter test"

[tasks.fmt]
run = "dart format ."

[tasks.check]
run = "flutter analyze"

[tasks.reload]
run = "[ -f .flutter.pid ] && kill -USR1 \"$( < .flutter.pid )\" || echo \"not running\""

[tasks.restart]
run = "[ -f .flutter.pid ] && kill -USR2 \"$( < .flutter.pid )\" || echo \"not running\""

[tasks."run:android"]
run         = "flutter run --pid-file=.flutter.pid"
description = "Runs the frontend (Android)"

[tasks."run:web"]
run         = "flutter run -d web-server --no-web-resources-cdn --wasm"
description = "Runs the frontend (web)"

[tasks."build:android"]
depends = "decrypt-signing"
run     = "flutter build apk"

[tasks."build:web"]
sources = ["pubspec.*", "assets/**/*", "lib/**/*.dart", "web/**/*"]
outputs = ["build/web-dist/**/*"]
run     = "flutter build web --release --no-web-resources-cdn -o build/web-dist"

[tasks."deploy:web"]
depends     = "build:web"
description = "Deploys the frontend to Cloudflare Pages"
run         = "wrangler pages deploy"

[tasks.decrypt-signing]
description = "Decrypt signing keystore"
sources     = ["android/signing/personal.keystore.age"]
outputs     = ["android/signing/personal.keystore"]
run         = "age -d -i ~/.config/age/key.txt -o android/signing/personal.keystore android/signing/personal.keystore.age"
