version: 2

updates:
  - package-ecosystem: npm
    directories:
      - /worker
      - /client
    schedule:
      interval: weekly
    # ideally picks it up from pnpm workspace?
    # cooldown:
    #   default-days: 7
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: pub
    directory: /client
    schedule:
      interval: weekly
    groups:
      pub-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
