monorepo_root = true

[env]
_.path = "~/Android/Sdk/platform-tools"

[monorepo]
config_roots = ["*"]

[tools]
java = "temurin-25"
node = "latest"

[tools.pnpm]
version     = "latest"
depends     = "node"
postinstall = "mise run //:setup:node"

[tools.flutter]
version          = "3.47"
platforms        = { linux-x64 = { checksum_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json", url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_{{ version }}-stable.tar.xz" }, macos-arm64 = { checksum_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json", url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_arm64_{{ version }}-stable.zip" }, macos-x64 = { checksum_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_macos.json", url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_{{ version }}-stable.zip" }, windows-x64 = { checksum_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_windows.json", url = "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_{{ version }}-stable.zip" } }
postinstall      = "mise run //:setup:flutter"
checksum_expr    = '"sha256:" + filter(fromJSON(body).releases, { #.archive endsWith filename })[0].sha256'
version_expr     = 'fromJSON(body).releases | filter({ #.channel == "stable" }) | map({ replace(#.version, "-stable", "") }) | sortVersions()'
version_list_url = "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"

[tools."http:android-cli"]
url         = "https://dl.google.com/android/cli/latest/{{os()}}_x86_64/android"
depends     = "flutter"
version     = "1.0"  # doesn't do anything ofc
postinstall = "mise run //:setup:android"

[shell_alias]
android = "android --no-metrics"

[tasks."setup:android"]
hide = true
run  = [
  "android",
  "android sdk install build-tools/37.0.0",
  "android sdk install platform-tools",
  "android sdk install cmdline-tools",
  "flutter doctor --android-licenses"
]

[tasks."setup:flutter"]
hide = true
run  = [
  "mise x -- dart --disable-analytics",
  "mise x -- flutter --disable-analytics",
  'mise set --env=local FLUTTER_ROOT="$(mise where flutter)"',
]

[tasks."setup:node"]
hide = true
dir  = "worker"
run  = ["pnpm install", "mise run //worker:cf-typegen"]
