org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This builtInKotlin flag was added automatically by Flutter migrator
# TODO: when in flutter >= 3.47
# https://docs.flutter.dev/release/breaking-changes/migrate-to-built-in-kotlin/for-app-developers
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
